remote_theme: bogstandard/lapland-golf-course
title: 'Lapland Golf Club'
description: '~ Grand Opening! Welcome Golfers! ~'
players:
  - username: 'bogstandard'
    name: 'Eric'
    index: 0
    url: 'https://github.com/bogstandard/adventofcode2021/blob/main/.scorecard'
